{-# LANGUAGE TemplateHaskell #-}

module ArrowTemplateHaskell
  ( MessageHeader(..)
  , Footer
  , BodyCompression
  , RecordBatch
  , DictionaryBatch
  , Block
  , MetadataVersion
  , Feature
  , Null
  , List
  , FixedSizeList
  , UnionMode
  , Map
  , TUnion
  , Binary
  , LargeList
  , LargeUtf8
  , TBool
  , RunEndEncoded
  , Schema
  , Field
  , Buffer
  , Endianness
  , CompressionType
  , FieldNode
  , Message
  , TInt
  , Type(..)
  , typeRunEndEncoded
  , typeLargeList
  , typeLargeUtf8
  , typeLargeBinary
  , typeDuration
  , typeMap
  , typeFixedSizeList
  , typeFixedSizeBinary
  , typeTUnion
  , typeTStruct
  , typeList
  , typeInterval
  , typeTimestamp
  , typeTime
  , typeDate
  , typeDecimal
  , typeTBool
  , typeUtf8
  , typeBinary
  , typeFloatingPoint
  , typeTInt
  , typeNull
  , utf8
  , timestampTimezone
  , timestampUnit
  , timestamp
  , timeBitWidth
  , timeUnit
  , tUnionTypeIds
  , tUnionMode
  , tUnion
  , tStruct
  , tIntIsSigned
  , tIntBitWidth
  , tInt
  , tBool
  , schemaFeatures
  , schemaCustomMetadata
  , schemaFields
  , schemaEndianness
  , runEndEncoded
  , mapKeysSorted
  , largeUtf8
  , largeList
  , largeBinary
  , keyValueValue
  , keyValueKey
  , keyValue
  , intervalUnit
  , interval
  , floatingPointPrecision
  , floatingPoint
  , fixedSizeListListSize
  , fixedSizeList
  , fixedSizeBinaryByteWidth
  , fixedSizeBinary
  , fieldCustomMetadata
  , fieldChildren
  , fieldDictionary
  , readType
  , fieldTyp
  , fieldNullable
  , field
  , durationUnit
  , duration
  , dictionaryEncodingDictionaryKind
  , dictionaryEncodingIsOrdered
  , dictionaryEncodingIndexType
  , dictionaryEncodingId
  , dictionaryEncoding
  , decimalBitWidth
  , decimalScale
  , decimalPrecision
  , decimal
  , dateUnit
  , bufferLength
  , bufferOffset
  , buffer
  , unionModeName
  , fromUnionMode
  , toUnionMode
  , timeUnitName
  , fromTimeUnit
  , toTimeUnit
  , precisionName
  , fromPrecision
  , toPrecision
  , metadataVersionName
  , fromMetadataVersion
  , toMetadataVersion
  , intervalUnitName
  , fromIntervalUnit
  , toIntervalUnit
  , featureName
  , fromFeature
  , toFeature
  , endiannessName
  , fromEndianness
  , toEndianness
  , dictionaryKindName
  , fromDictionaryKind
  , toDictionaryKind
  , dateUnitName
  , fromDateUnit
  , toDateUnit
  , date
  , fieldName
  , schema
  , null
  , list
  , map
  , time
  , binary
  , tensorDimName
  , tensorDimSize
  , tensorDim
  , tensorDat
  , tensorStrides
  , tensorShape
  , tensorTyp
  , tensor
  , sparseTensorIndexSparseTensorIndexCSF
  , sparseTensorIndexSparseMatrixIndexCSX
  , sparseTensorIndexSparseTensorIndexCOO
  , sparseTensorIndexCSFAxisOrder
  , sparseTensorIndexCSFIndicesBuffers
  , sparseTensorIndexCSFIndicesType
  , sparseTensorIndexCSFIndptrBuffers
  , sparseTensorIndexCSFIndptrType
  , sparseTensorIndexCSF
  , sparseTensorIndexCOOIsCanonical
  , sparseTensorIndexCOOIndicesBuffer
  , sparseTensorIndexCOOIndicesStrides
  , sparseTensorIndexCOOIndicesType
  , sparseTensorIndexCOO
  , sparseTensorDat
  , readSparseTensorIndex
  , sparseTensorSparseIndex
  , sparseTensorNonZeroLength
  , sparseTensorShape
  , sparseTensorTyp
  , sparseTensor
  , sparseMatrixIndexCSXIndicesBuffer
  , sparseMatrixIndexCSXIndicesType
  , sparseMatrixIndexCSXIndptrBuffer
  , sparseMatrixIndexCSXIndptrType
  , sparseMatrixIndexCSXCompressedAxis
  , sparseMatrixIndexCSX
  , sparseMatrixCompressedAxisName
  , fromSparseMatrixCompressedAxis
  , toSparseMatrixCompressedAxis
  , footerCustomMetadata
  , footerRecordBatches
  , footerDictionaries
  , footerSchema
  , footerVersion
  , footer
  , blockBodyLength
  , blockMetaDataLength
  , blockOffset
  , block
  , messageHeaderSparseTensor
  , messageHeaderTensor
  , messageHeaderRecordBatch
  , messageHeaderDictionaryBatch
  , messageHeaderSchema
  , recordBatchCompression
  , recordBatchBuffers
  , recordBatchNodes
  , recordBatchLength
  , recordBatch
  , messageCustomMetadata
  , messageBodyLength
  , readMessageHeader
  , messageHeader
  , messageVersion
  , message
  , dictionaryBatchIsDelta
  , dictionaryBatchDat
  , dictionaryBatchId
  , dictionaryBatch
  , bodyCompressionMethod
  , bodyCompressionCodec
  , bodyCompression
  , fieldNodeNullCount
  , fieldNodeLength
  , fieldNode
  , compressionTypeName
  , fromCompressionType
  , toCompressionType
  , bodyCompressionMethodName
  , fromBodyCompressionMethod
  , toBodyCompressionMethod
  ) where

import Prelude hiding (map,null)

import FlatBuffers


$(mkFlatBuffers "arrow-format/Schema.fbs" defaultOptions)
$(mkFlatBuffers "arrow-format/Tensor.fbs" defaultOptions)
$(mkFlatBuffers "arrow-format/SparseTensor.fbs" defaultOptions)
$(mkFlatBuffers "arrow-format/File.fbs" defaultOptions)
$(mkFlatBuffers "arrow-format/Message.fbs" defaultOptions)
